/**
 * @file discount.service.ts
 * @description Business logic for discount validation and generation.
 */

import { globalStore } from '../store';

export const DiscountService = {
    /**
     * Checks if a code is valid (exists and unused).
     * Rule: Only codes generated by the system milestones are valid.
     */
    validateCode(code: string): { valid: boolean; percentage?: number } {
        return globalStore.validateDiscount(code);
    },

    /**
     * Generates a new discount code for a specific order.
     * Rule: Uses the store's configured percentage and tracks source order.
     */
    generateMilestoneCode(orderId: string): string {
        const code = `DISCOUNT_${Date.now()}#${Math.floor(Math.random() * 1000)}`;
        globalStore.addDiscountCode(code, orderId);
        return code;
    },

    /**
     * Manually triggers reward generation for the current milestone.
     */
    manualGenerate(): string | null {
        const orders = globalStore.getOrders();
        const currentCount = orders.length;
        const nth = globalStore.getState().nthOrderCount;

        if (currentCount > 0 && currentCount % nth === 0) {
            // Check if a code already exists for the latest order
            const lastOrder = orders[orders.length - 1];
            const alreadyGenerated = globalStore.getDiscountCodes().some(dc => dc.orderIdGeneratedFrom === lastOrder?.id);

            if (!alreadyGenerated && lastOrder) {
                return this.generateMilestoneCode(lastOrder.id);
            }
        }
        return null;
    },

    /**
     * Returns the current order count and the configured threshold.
     */
    getMilestoneInfo() {
        const state = globalStore.getState();
        return {
            currentCount: state.orders.length,
            nth: state.nthOrderCount
        };
    }
};
