/**
 * @file discount.service.ts
 * @description Business logic for discount validation and generation.
 */

import { globalStore } from '../store';

export const DiscountService = {
    /**
     * Checks if a code is valid (exists and unused).
     * Rule: Only codes generated by the system milestones are valid.
     */
    validateCode(code: string): { valid: boolean; percentage?: number } {
        return globalStore.validateDiscount(code);
    },

    /**
     * Generates a new discount code for a specific order.
     * Rule: Uses the store's configured percentage and tracks source order.
     */
    generateMilestoneCode(orderId: string): string {
        const code = `DISCOUNT_${Date.now()}#${Math.floor(Math.random() * 1000)}`;
        globalStore.addDiscountCode(code, orderId);
        return code;
    },

    /**
     * Manually triggers code generation if milestone is met.
     */
    manualGenerate(): string | null {
        return globalStore.manualDiscountGeneration();
    },

    /**
     * Returns the current order count and the configured threshold.
     */
    getMilestoneInfo() {
        const state = globalStore.getState();
        return {
            currentCount: state.orders.length,
            nth: state.nthOrderCount
        };
    }
};
